apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testetst"
  description: "testst"
  annotations:
    github.com/project-slug: ravargs/testtest
    backstage.io/techdocs-ref: url:https://github.com/ravargs/testtest
spec:
  type: service
  lifecycle: experimental
  owner: "ravargs"
